Numpy Basics
1. Given array a = [30, 45, 22, 75, 84] and array b = [67, 40, 90, 13, 56]:
a. For every element e in a and b, calculate and print whether a[e] > b[e].
b. Use a binary mask to change all values where a[e] > 30 to be set to 50.


In [9]:
import numpy as np

a = np.array([30, 45, 22, 75, 84])
b = np.array([67, 40, 90, 13, 56])
for e in range(5):
  print(a[e] > b[e])

a[a > 30] = 50
print(a)

False
True
False
True
True
[30 50 22 50 50]


2. Given array x = [[5, 2, 6, 1], [3, 4, 7, 2], [8, 1, 2, 9], [3, 4, 2, 6]], calculate the sum of the
highlighted and bolded elements using indexing.


In [10]:
x = np.array([[5, 2, 6, 1], [3, 4, 7, 2], [8, 1, 2, 9], [3, 4, 2, 6]])

print(x[0, 2] + x[3, 1])

10


3. Given array c = [[1, 0], [8, 1]] and array d = [[4, 1], [2, 2]], calculate the dot product of c
and d.


In [11]:
c = np.array([[1, 0], [8, 1]])
d = np.array([[4, 1], [2, 2]])

print(np.dot(c,d))

[[ 4  1]
 [34 10]]


4. Given array a = [[1, 4], [2, 9], [5, 6]], find the shape and transpose of a.


In [12]:
a = np.array([[1, 4], [2, 9], [5, 6]])
print(a.shape)

(3, 2)


5. Given array x = [[1, 2], [3, 4]] and array y = [[5, 6], [7, 8], [9, 0]], stack the arrays in
sequence vertically.



In [13]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8], [9, 0]])

np.vstack([x,y])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

Area and Probability with Numpy

Hint: for all of the following problems, look into different ways you can use np.random.
6. Calculate the area of x^2 + y^2 ≤ 1 by uniformly sampling x in [-1,1] and y in [-1,1]

In [14]:
import numpy as np

trial = 10000
x = np.random.uniform(-1, 1, size = trial)
y = np.random.uniform(-1, 1, size = trial)
z = x**2 + y**2

print(np.sum(z <= 1)/trial)

0.7863


7. Calculate the probability that x^2 + y^2 ≤ 1 if x and y are two standard Gaussian
distribution variables.

In [15]:
import numpy as np

trial = 100000
x = np.random.randn(trial)
y = np.random.randn(trial)
z = x**2 + y**2

print(np.sum(z <= 1)/trial)

0.3959


In [16]:
def Gaussian_distribution(trail):
  x = np.random.randn(trial)
  y = np.random.randn(trial)
  z = x**2 + y**2
  prob = np.sum(z <= 1)/trial
  return prob

for i in [100, 1000, 10000, 10000]:
  print(f'After trying {i} times, the area of x**2 + y**2 <=1 is estimated to be {Gaussian_distribution(i)}')

After trying 100 times, the area of x**2 + y**2 <=1 is estimated to be 0.39325
After trying 1000 times, the area of x**2 + y**2 <=1 is estimated to be 0.39232
After trying 10000 times, the area of x**2 + y**2 <=1 is estimated to be 0.39329
After trying 10000 times, the area of x**2 + y**2 <=1 is estimated to be 0.39137


8. Calculate the probability that the sum of three dice is larger than 10 if you randomly roll the three dice.

In [17]:
import numpy as np

def prob(trail):
  sample_data = np.random.randint(1,7,size = trail*3)
  experitiments = sample_data.reshape(trail, 3)
  results = experitiments.sum(-1)
  larger_than_ten = np.sum(results < 10)
  pb = larger_than_ten / trail
  return pb

for i in [100, 1000, 10000, 100000]:
  print(f'After trying {i} times, the probability that sum of three dice larger than 10 is {prob(i)} ')

After trying 100 times, the probability that sum of three dice larger than 10 is 0.37 
After trying 1000 times, the probability that sum of three dice larger than 10 is 0.384 
After trying 10000 times, the probability that sum of three dice larger than 10 is 0.3813 
After trying 100000 times, the probability that sum of three dice larger than 10 is 0.37653 
